from fpdf import FPDF
from datetime import datetime
import os

def clean_text(text):
    if not text:
        return ""

    text = (
        str(text)
        .replace("—", "-")
        .replace("–", "-")
        .replace("•", "-")
        .replace("★", "*")
        .replace("🌟", "*")
        .replace("📍", "")
        .replace("💰", "Rs.")
        .replace("🗓", "")
        .replace("✨", "")
    )

    # Remove any remaining unsupported unicode chars
    text = text.encode("ascii", "ignore").decode("ascii")

    return text


class ItineraryPDF(FPDF):

    def header(self):
        # Gradient-style header bar
        self.set_fill_color(11, 61, 46)   # dark green
        self.rect(0, 0, 210, 28, "F")
        self.set_fill_color(20, 90, 69)
        self.rect(0, 20, 210, 8, "F")

        self.set_font("Helvetica", "B", 20)
        self.set_text_color(255, 255, 255)
        self.set_xy(0, 6)
        self.cell(210, 10, "HIMALAYA TRAVEL", align="C")

        self.set_font("Helvetica", "", 9)
        self.set_text_color(180, 230, 200)
        self.set_xy(0, 16)
        self.cell(210, 6, "AI-Powered Personalized Itinerary", align="C")
        self.ln(14)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by Himalaya AI  |  {datetime.now().strftime('%d %B %Y')}", align="C")

    def section_title(self, title, color=(11, 61, 46)):
        self.set_fill_color(*color)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 11)
        self.cell(0, 8, f"  {title}", fill=True, ln=True)
        self.ln(2)

    def info_row(self, label, value):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(80, 80, 80)
        self.cell(45, 6, label)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(30, 30, 30)
        self.cell(0, 6, str(value), ln=True)

    def place_card(self, place, index):
        x = self.get_x()
        y = self.get_y()

        # Card background
        self.set_fill_color(245, 250, 247)
        self.set_draw_color(200, 225, 210)
        self.rect(14, y, 182, 26, "FD")

        # Index badge
        self.set_fill_color(11, 61, 46)
        self.set_xy(16, y + 2)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(255, 255, 255)
        self.cell(10, 7, str(index), align="C", fill=True)

        # Place name
        self.set_xy(28, y + 2)
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(11, 61, 46)
        place_name = place.get("place_name", "")
        self.cell(100, 7, place_name)

        # Category badge
        self.set_xy(140, y + 2)
        self.set_fill_color(224, 242, 232)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(11, 80, 46)
        self.cell(40, 7, place.get("category", ""), align="C", fill=True)

        # Details row
        self.set_xy(28, y + 10)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(90, 90, 90)
        cost = place.get("avg_cost", 0)
        duration = place.get("visit_duration_hours", "")
        best_time = place.get("best_time", "")
        self.cell(0, 5, f"Cost: Rs.{cost}   |   Duration: {duration}h   |   Best time: {best_time}")

        # Description
        desc = place.get("description", "")
        if desc:
            self.set_xy(28, y + 16)
            self.set_font("Helvetica", "I", 7.5)
            self.set_text_color(110, 110, 110)
            # Truncate long descriptions
            if len(desc) > 95:
                desc = desc[:92] + "..."
            self.cell(0, 5, desc)

        # Tip (if LLM-generated)
        tip = place.get("tip", "")
        if tip:
            self.set_xy(28, y + 21)
            self.set_font("Helvetica", "B", 7.5)
            self.set_text_color(20, 90, 69)
            if len(tip) > 90:
                tip = tip[:87] + "..."
            self.cell(5, 4, "*")
            self.set_font("Helvetica", "", 7.5)
            self.cell(0, 4, tip)

        self.set_y(y + 29)


def generate_itinerary_pdf(itinerary_data: dict) -> bytes:
    """
    Generate a styled PDF for the itinerary.
    Returns PDF as bytes (to stream as HTTP response).
    """
    pdf = ItineraryPDF()
    pdf.set_auto_page_break(auto=True, margin=16)
    pdf.add_page()

    # ── COVER SECTION ──────────────────────────────────────
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(11, 61, 46)
    pdf.cell(0, 12, "YOUR PERSONALIZED JOURNEY", align="C", ln=True)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 7, "Sikkim, India - AI-Crafted Itinerary", align="C", ln=True)
    pdf.ln(4)

    # ── TRIP OVERVIEW ──────────────────────────────────────
    pdf.section_title("TRIP OVERVIEW")

    profile = itinerary_data.get("traveler_profile", "Explorer")
    cost = itinerary_data.get("estimated_cost", 0)
    days = len(itinerary_data.get("itinerary", {}))
    ai_powered = itinerary_data.get("ai_powered", False)
    start_date = itinerary_data.get("start_date", "")
    hidden_gem = itinerary_data.get("hidden_gem")

    pdf.info_row("Traveler Profile:", profile)
    pdf.info_row("Trip Duration:", f"{days} Days")
    if start_date:
        pdf.info_row("Start Date:", start_date)
    pdf.info_row("Estimated Cost:", f"Rs. {cost:,}")
    pdf.info_row("Itinerary Type:", "AI-Generated (Gemini)" if ai_powered else "Smart Curated")
    pdf.ln(3)

    # ── AI NARRATIVE ──────────────────────────────────────
    ai_narrative = itinerary_data.get("ai_narrative")
    if ai_narrative:
        pdf.section_title("AI TRAVEL NARRATIVE", color=(20, 90, 69))
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(40, 40, 40)
        pdf.multi_cell(0, 6, clean_text(ai_narrative))
        pdf.ln(3)

    # ── HIDDEN GEM ──────────────────────────────────────
    if hidden_gem:
        pdf.set_fill_color(255, 248, 220)
        pdf.set_draw_color(220, 170, 0)
        pdf.set_xy(14, pdf.get_y())
        pdf.rect(14, pdf.get_y(), 182, 14, "FD")
        pdf.set_xy(16, pdf.get_y() + 2)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(140, 100, 0)
        gem_name = hidden_gem.get("place_name", "")
        pdf.cell(0, 5, f" Hidden Gem: {gem_name}", ln=True)
        pdf.set_xy(16, pdf.get_y())
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(100, 70, 0)
        pdf.cell(
    0,
    5,
    clean_text(
        f"{hidden_gem.get('description', '')} - Popularity Score: {hidden_gem.get('popularity_score', '')}/100"
    )
)
        pdf.ln(10)

    # ── DAY-BY-DAY ITINERARY ──────────────────────────────
    itinerary = itinerary_data.get("itinerary", {})

    day_colors = [
        (11, 61, 46),
        (20, 80, 100),
        (80, 40, 100),
        (140, 60, 20),
        (20, 100, 80),
        (60, 20, 80),
        (100, 20, 40),
    ]

    for i, (day_label, day_data) in enumerate(itinerary.items()):
        color = day_colors[i % len(day_colors)]
        region = day_data.get("region", "")
        theme = day_data.get("theme", "")
        day_summary = day_data.get("day_summary", "")

        # Day header
        pdf.section_title(
            f"{day_label.upper()}  |  {region}" + (f"  -  {theme}" if theme else ""),
            color=color
        )

        if day_summary:
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(70, 70, 70)
            pdf.cell(0, 5, clean_text(day_summary), ln=True)
            pdf.ln(1)

        places = day_data.get("places", [])
        for j, place in enumerate(places):
            pdf.place_card(place, j + 1)

        pdf.ln(4)

    # ── COST BREAKDOWN ──────────────────────────────────────
    pdf.add_page()
    pdf.section_title("ESTIMATED COST BREAKDOWN")

    people = itinerary_data.get("people", 1)
    days_count = len(itinerary)

    hotel_cost = days_count * 2500
    food_cost = days_count * people * 800
    transport_cost = days_count * 1000

    all_places = []
    for day_data in itinerary.values():
        all_places.extend(day_data.get("places", []))
    attraction_cost = sum(p.get("avg_cost", 0) for p in all_places)

    rows = [
        ("Attractions & Entry Fees", f"Rs. {attraction_cost:,}"),
        (f"Accommodation ({days_count} nights)", f"Rs. {hotel_cost:,}"),
        (f"Food & Dining ({people} people)", f"Rs. {food_cost:,}"),
        ("Local Transport", f"Rs. {transport_cost:,}"),
        ("TOTAL ESTIMATED COST", f"Rs. {cost:,}"),
    ]

    for label, value in rows:
        is_total = "TOTAL" in label
        pdf.set_fill_color(11, 61, 46) if is_total else pdf.set_fill_color(245, 250, 247)
        pdf.set_text_color(255, 255, 255) if is_total else pdf.set_text_color(30, 30, 30)
        pdf.set_font("Helvetica", "B" if is_total else "", 10)
        pdf.set_draw_color(200, 225, 210)
        pdf.cell(130, 9, f"  {label}", border=1, fill=True)
        pdf.cell(52, 9, value, border=1, align="R", fill=True, ln=True)

    # ── TRAVEL TIP ──────────────────────────────────────
    tip = itinerary_data.get("travel_tip", "")
    if tip:
        pdf.ln(6)
        pdf.set_fill_color(232, 245, 240)
        pdf.set_draw_color(11, 61, 46)
        y = pdf.get_y()
        pdf.rect(14, y, 182, 14, "FD")
        pdf.set_xy(16, y + 2)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(11, 61, 46)
        pdf.cell(0, 5, "TRAVEL TIP", ln=True)
        pdf.set_xy(16, pdf.get_y())
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 5, clean_text(tip))

    return bytes(pdf.output())
